import type { GameDef } from './cognitive'

export const GAMES: GameDef[] = [
  {
    id: 'matrix-forge',
    title: 'Matrix Forge',
    subtitle: 'Advanced pattern matrices',
    category: 'iq-arena',
    targets: ['pattern-recognition', 'spatial-reasoning', 'executive-function'],
    difficulty: 'intermediate',
    players: '1',
    duration: '5-10 min',
    description: 'Solve increasingly complex visual pattern matrices. Find the missing piece by identifying relationships across rows, columns, and diagonals.',
  },
  {
    id: 'sequence-collapse',
    title: 'Sequence Collapse',
    subtitle: 'Predict what comes next',
    category: 'iq-arena',
    targets: ['pattern-recognition', 'processing-speed', 'probabilistic-reasoning'],
    difficulty: 'intermediate',
    players: '1',
    duration: '3-8 min',
    description: 'Numbers, colors, symbols — predict the next element in increasingly complex sequences. Multiple correct strategies exist.',
  },
  {
    id: 'split-decision',
    title: 'Split Decision',
    subtitle: 'Three things at once',
    category: 'fast-brain',
    targets: ['processing-speed', 'decision-making', 'executive-function'],
    difficulty: 'intermediate',
    players: '1',
    duration: '2-5 min',
    description: 'Three scenarios appear simultaneously. Choose the fastest, safest, or smartest option within 2 seconds. Your brain learns prioritization.',
  },
  {
    id: 'signal-noise',
    title: 'Signal vs Noise',
    subtitle: 'Find what matters',
    category: 'fast-brain',
    targets: ['sustained-attention', 'processing-speed', 'visual-perception'],
    difficulty: 'advanced',
    players: '1',
    duration: '3-7 min',
    description: 'Floods of information. Distractions everywhere. Find the meaningful signal. Inspired by intelligence analysts.',
  },
  {
    id: 'word-forge',
    title: 'Word Forge',
    subtitle: 'Build complex words',
    category: 'language-arena',
    targets: ['linguistic-fluency', 'working-memory', 'creativity'],
    difficulty: 'beginner',
    players: '1',
    duration: '5-10 min',
    description: 'Build increasingly complex words by chaining letters. Score multipliers for longer words, rare letters, and cross-language connections.',
  },
  {
    id: 'impossible-uses',
    title: 'Impossible Uses',
    subtitle: 'Divergent thinking',
    category: 'creativity-lab',
    targets: ['creativity', 'cognitive-flexibility', 'linguistic-fluency'],
    difficulty: 'beginner',
    players: '1',
    duration: '3-5 min',
    description: 'Given an everyday object, generate as many unexpected uses as possible. Originality scores highest — not correctness.',
  },
  {
    id: 'memory-marathon',
    title: 'Memory Marathon',
    subtitle: 'Remember 10, then 100',
    category: 'mental-endurance',
    targets: ['working-memory', 'sustained-attention', 'visual-perception'],
    difficulty: 'intermediate',
    players: '1',
    duration: '5-15 min',
    description: 'Objects flash on screen. Remember their positions. 10, then 20, then 40, then 100. How far can you go?',
  },
  {
    id: 'focus-tower',
    title: 'Focus Tower',
    subtitle: '30 minutes of pure focus',
    category: 'mental-endurance',
    targets: ['sustained-attention', 'executive-function', 'cognitive-flexibility'],
    difficulty: 'advanced',
    players: '1',
    duration: '10-30 min',
    description: 'Build a tower of concentration. Distractions increase every level. One mistake and floors crumble. Pure sustained attention training.',
  },
  {
    id: 'cognitive-overload',
    title: 'Cognitive Overload',
    subtitle: 'Filter what matters',
    category: 'fast-brain',
    targets: ['executive-function', 'processing-speed', 'decision-making'],
    difficulty: 'expert',
    players: '1',
    duration: '3-8 min',
    description: 'Information keeps increasing. Player must filter what matters while ignoring noise. Similar to emergency medicine triage.',
  },
  {
    id: 'pattern-hunter',
    title: 'Pattern Hunter',
    subtitle: 'Find hidden rules',
    category: 'iq-arena',
    targets: ['pattern-recognition', 'executive-function', 'sustained-attention'],
    difficulty: 'advanced',
    players: '1',
    duration: '5-12 min',
    description: 'Huge beautiful patterns. Find the hidden mathematical rules governing them. Beware — some patterns are decoys.',
  },
  {
    id: 'spatial-architect',
    title: 'Spatial Architect',
    subtitle: 'Rotate impossible objects',
    category: 'iq-arena',
    targets: ['spatial-reasoning', 'visual-perception', 'working-memory'],
    difficulty: 'advanced',
    players: '1',
    duration: '5-10 min',
    description: 'Mentally rotate 3D objects, fold paper, predict intersections. Like engineering aptitude tests turned beautiful.',
  },
  {
    id: 'moral-dilemmas',
    title: 'Moral Dilemmas',
    subtitle: 'No correct answers',
    category: 'psychological',
    targets: ['decision-making', 'theory-of-mind', 'emotional-intelligence'],
    difficulty: 'intermediate',
    players: '1',
    duration: '5-10 min',
    description: 'Interactive moral scenarios. No right answers. Reveals your decision profile — utilitarian, deontological, or virtue-based.',
  },
  {
    id: 'risk-appetite',
    title: 'Risk Appetite',
    subtitle: 'Discover your true risk tolerance',
    category: 'psychological',
    targets: ['decision-making', 'probabilistic-reasoning', 'emotional-intelligence'],
    difficulty: 'beginner',
    players: '1',
    duration: '5-8 min',
    description: 'Investment, health, relationships, business. Repeated experiments reveal your actual — not perceived — risk tolerance.',
  },
  {
    id: 'brick-breaker',
    title: 'Brick Breaker',
    subtitle: 'Classic arcade',
    category: 'classic',
    targets: ['processing-speed', 'spatial-reasoning', 'sustained-attention'],
    difficulty: 'beginner',
    players: '1',
    duration: '5-15 min',
    description: 'The timeless brick-breaking game with modern physics, power-ups, and beautiful visuals. Pure arcade joy.',
  },
  {
    id: 'tetris-flow',
    title: 'Block Flow',
    subtitle: 'Spatial stacking',
    category: 'classic',
    targets: ['spatial-reasoning', 'processing-speed', 'pattern-recognition'],
    difficulty: 'beginner',
    players: '1',
    duration: '5-20 min',
    description: 'Falling blocks, spatial reasoning, fast decisions. A cognitive classic reimagined with fluid aesthetics.',
  },
  {
    id: 'diagnosis-sprint',
    title: 'Diagnosis Sprint',
    subtitle: 'Clinical reasoning under pressure',
    category: 'medical',
    targets: ['decision-making', 'pattern-recognition', 'probabilistic-reasoning'],
    difficulty: 'expert',
    players: '1',
    duration: '5-10 min',
    description: 'Receive symptoms, choose tests, manage budget and time. Lives matter. Evidence-based clinical decision-making.',
  },
  {
    id: 'debate-ai',
    title: 'Debate the AI',
    subtitle: 'Argue your case',
    category: 'ai-games',
    targets: ['linguistic-fluency', 'creativity', 'decision-making'],
    difficulty: 'advanced',
    players: '1',
    duration: '5-10 min',
    description: 'Pick a topic and argue against an AI opponent. Scored on logic, evidence, persuasion, and rhetorical skill.',
  },
  {
    id: 'truth-or-dare',
    title: 'Truth or Dare',
    subtitle: 'Spicy party dares',
    category: 'party',
    targets: ['social-intelligence', 'emotional-intelligence', 'creativity'],
    difficulty: 'beginner',
    players: '2-8',
    duration: '10-30 min',
    description: 'The ultimate party game. Choose truth or dare, face your fears, and discover secrets about your friends, partner, or siblings.',
  },
  {
    id: 'never-have-i-ever',
    title: 'Never Have I Ever',
    subtitle: 'Reveal your secrets',
    category: 'party',
    targets: ['social-intelligence', 'theory-of-mind', 'emotional-intelligence'],
    difficulty: 'beginner',
    players: '2-10',
    duration: '10-20 min',
    description: 'Discover what your friends have (or haven\'t) done. Start with 10 lives — each "I have" costs you one. Last one standing wins.',
  },
  {
    id: 'guess-what',
    title: 'Guess What',
    subtitle: 'How well do you know them?',
    category: 'party',
    targets: ['theory-of-mind', 'social-intelligence', 'emotional-intelligence'],
    difficulty: 'beginner',
    players: '2-4',
    duration: '10-20 min',
    description: 'How well do you really know each other? One player answers secretly, others guess. Reveals who truly understands you.',
  },
  {
    id: 'draft-chase',
    title: 'Draft & Chase',
    subtitle: 'Beat their score',
    category: 'party',
    targets: ['processing-speed', 'working-memory', 'decision-making'],
    difficulty: 'intermediate',
    players: '2',
    duration: '5-10 min',
    description: 'Head-to-head mini-challenges. One sets the score, the other chases it. Best of 5 rounds. Fast, dramatic, addictive.',
  },
  {
    id: 'snake',
    title: 'Snake',
    subtitle: 'Classic arcade serpent',
    category: 'classic',
    targets: ['processing-speed', 'spatial-reasoning', 'sustained-attention'],
    difficulty: 'beginner',
    players: '1',
    duration: '2-10 min',
    description: 'The timeless arcade game. Eat, grow, survive. Speed increases as you grow longer. How far can you go?',
  },
  {
    id: 'last-card',
    title: 'Last Card',
    subtitle: 'Shed all your cards',
    category: 'card-games',
    targets: ['strategic-planning', 'pattern-recognition', 'decision-making'],
    difficulty: 'beginner',
    players: '2-4',
    duration: '10-20 min',
    description: 'The classic card-shedding game. Match suit or rank, stack +2s, reverse, skip. First to empty their hand wins.',
  },
  {
    id: 'albastini',
    title: 'Albastini',
    subtitle: 'East African card battle',
    category: 'card-games',
    targets: ['strategic-planning', 'working-memory', 'probabilistic-reasoning'],
    difficulty: 'intermediate',
    players: '2-4',
    duration: '10-25 min',
    description: 'The beloved East African trick-taking card game. Read your opponents, play your trumps, dominate the table.',
  },
  {
    id: 'monopoly',
    title: 'Monopoly',
    subtitle: 'Build your empire',
    category: 'board-games',
    targets: ['strategic-planning', 'negotiation', 'probabilistic-reasoning'],
    difficulty: 'intermediate',
    players: '2-4',
    duration: '20-60 min',
    description: 'Buy properties, build houses and hotels, collect rent, bankrupt your opponents. The classic real estate tycoon board game.',
  },
  {
    id: 'calisthenics',
    title: 'Calisthenics',
    subtitle: 'Body weight challenges',
    category: 'fitness',
    targets: ['sustained-attention', 'decision-making', 'executive-function'],
    difficulty: 'intermediate',
    players: '1',
    duration: '5-20 min',
    description: 'Scientifically structured bodyweight exercise challenges. Progressive difficulty, proper form guidance, rep tracking, and rest timers.',
  },
  {
    id: 'breath-hold',
    title: 'Breath Hold',
    subtitle: 'Master your breathing',
    category: 'fitness',
    targets: ['sustained-attention', 'executive-function', 'emotional-intelligence'],
    difficulty: 'beginner',
    players: '1',
    duration: '3-10 min',
    description: 'Breathing exercises backed by science. Box breathing, Wim Hof method, apnea training. Track your progress and build lung capacity.',
  },
  {
    id: 'scripture-quest',
    title: 'Scripture Quest',
    subtitle: 'Test your spiritual knowledge',
    category: 'faith',
    targets: ['working-memory', 'pattern-recognition', 'linguistic-fluency'],
    difficulty: 'intermediate',
    players: '1',
    duration: '5-15 min',
    description: 'Deep knowledge challenges across major world faiths. Bible, Quran, Torah, Bhagavad Gita, Buddhist sutras. Respectful, educational, scholarly.',
  },
  {
    id: 'spin-the-bottle',
    title: 'Spin the Bottle',
    subtitle: 'Dare to spin',
    category: 'couples',
    targets: ['social-intelligence', 'emotional-intelligence', 'creativity'],
    difficulty: 'beginner',
    players: '2-8',
    duration: '10-30 min',
    description: 'The classic spin game with custom questions and challenges. Add your own dares or use the built-in comprehensive question bank.',
  },
  {
    id: 'couples-quiz',
    title: 'Couples Quiz',
    subtitle: 'How well do you know each other?',
    category: 'couples',
    targets: ['theory-of-mind', 'social-intelligence', 'emotional-intelligence'],
    difficulty: 'beginner',
    players: '2',
    duration: '10-20 min',
    description: 'Deep relationship quiz covering love languages, memories, preferences, dreams, and intimacy. Strengthen your bond through discovery.',
  },
]

export function getGame(id: string): GameDef | undefined {
  return GAMES.find(g => g.id === id)
}

export function getGamesByCategory(cat: string): GameDef[] {
  return GAMES.filter(g => g.category === cat)
}
